### ISSUE TITLE
register webview

### ISSUE THREAD

**Issue by bboydflo** [GeorgeArgyrakis/FloatingKeyboard#1]
Hello, and thanks for this small library. 
I want to use it together with a WebView. how should I achieve that?

**Comment by GeorgeArgyrakis** [comment]
The easiest way would be to keep it always open. Otherwise you should find a way to register it with the webview (it does not seem an easy task)

**Comment by arislomovic** [comment]
Any way to get this working with an InputMethodService? I tried including it in a relativelayout, but ut seems to just stay put on the bottom?

**Comment by GeorgeArgyrakis** [comment]
@arislomovic I have not use InputMethodService before so i do not know. Can you move the keyboard in the sample app?

**Comment by arislomovic** [comment]
Hi, 

Sorry for the delayed response. I inflated the keyboard in onCreateCandidatesView instead of onCreateInputView, which allowed you to create a floating system keyboard in InputMethodService. I did have to put the FKV into a relative layout and set the margins, though, but it worked perfectly.
